"""
Test real VLM (LLaVA) with your somatosensory PDF.

This will:
1. Extract diagram from your PDF
2. Use LLaVA to generate a REAL diagram-based question
3. Show you the difference from mock questions
"""

from pathlib import Path
from pdf_extractor import extract_pdf, create_text_image_pairs
from multimodal_generator import MultimodalMCQGenerator
from vlm_client import VLMConfig, VLMClient
from models import DifficultyLevel

print("\n" + "="*80)
print("TESTING REAL VLM (LLaVA) WITH YOUR PDF")
print("="*80)

pdf_path = "/Users/kairavparikh/Downloads/somatosensory.pdf"

if not Path(pdf_path).exists():
    print(f"\n❌ PDF not found: {pdf_path}")
    exit(1)

# Step 1: Extract PDF
print(f"\n📄 Extracting diagrams from: {Path(pdf_path).name}")
pdf_doc = extract_pdf(pdf_path, pages=[1, 2, 3])

print(f"   ✅ Found {pdf_doc.total_images} diagram(s)")

# Step 2: Create pairs
pairs = create_text_image_pairs(pdf_doc)

if not pairs:
    print("\n❌ No diagrams found in PDF")
    exit(1)

print(f"   ✅ Created {len(pairs)} text-image pair(s)")

# Step 3: Set up REAL VLM (LLaVA)
print(f"\n⚡ Setting up LLaVA...")
vlm_config = VLMConfig(
    base_url="http://localhost:11434",
    model_name="llava",
    timeout_seconds=180
)
vlm_client = VLMClient(vlm_config)

# Test connection
if not vlm_client.test_connection():
    print("❌ LLaVA not available. Make sure: ollama serve")
    exit(1)

print(f"   ✅ LLaVA connected and ready")

# Step 4: Generate REAL diagram-based question
print(f"\n🤖 Generating diagram-based question with LLaVA...")
print(f"   (This may take 60-120 seconds)")

generator = MultimodalMCQGenerator(vlm_client=vlm_client)

try:
    questions = generator.generate_from_pair(
        pair=pairs[0],
        subject="Sensory Systems",
        main_topic="Somatosensory System",
        subtopic="Muscle Spindles",
        difficulty=DifficultyLevel.MEDIUM,
        n=1  # Generate 1 question
    )

    if questions:
        q = questions[0]

        print("\n" + "="*80)
        print("✅ REAL DIAGRAM-BASED QUESTION GENERATED!")
        print("="*80)

        print(f"\n📊 Source Diagram: Page {pairs[0].page_number}")
        print(f"   Caption: {pairs[0].images[0].caption[:80]}...")

        print(f"\n❓ Question:")
        print(f"   {q.question_text_en}")

        print(f"\n   Options:")
        for label, text in q.get_options_dict().items():
            marker = "✅" if label == q.correct_answer else "  "
            print(f"   {marker} {label}) {text}")

        print(f"\n   ✓ Correct: {q.correct_answer}")

        print(f"\n💡 Explanation:")
        print(f"   {q.explanation}")

        print(f"\n📚 References:")
        for ref in q.references:
            print(f"   • {ref}")

        print("\n" + "="*80)
        print("✅ REAL VLM TEST SUCCESSFUL!")
        print("="*80)

        print("\nThis question was generated by LLaVA LOOKING AT the diagram!")
        print("It understands the visual content and creates relevant questions.")

    else:
        print("\n❌ No questions generated")

except Exception as e:
    print(f"\n❌ Error: {e}")
    import traceback
    traceback.print_exc()

print("\n" + "="*80)
